### ISSUE TITLE
Add templates for ALTER statements

### ISSUE THREAD

**Issue by SloNN** [ydb-platform/ydb-embedded-ui#1022]
for all kinds of entities: row-based table, column-based, topics.

**Comment by SloNN** [comment]
Accidentially found it here. I think we should add a more obvious place to show this.
![image](https://github.com/user-attachments/assets/649f0173-b6ea-4bb7-9b27-f6623d49b784)

**Comment by antonkovalenko** [comment]
Will be improved in [#1153](https://github.com/ydb-platform/ydb-embedded-ui/issues/1153)

**Comment by antonkovalenko** [comment]
@antonkovalenko will hadd query templates for alter table (sec indexes and friends), topics and other entities.
queries are to be places to right menu and three dots

**Comment by artemmufazalov** [comment]
@antonkovalenko all template are here:

"New SQL" button:
https://github.com/ydb-platform/ydb-embedded-ui/blob/main/src/containers/Tenant/utils/newSQLQueryTemplates.ts

Dots in schema tree:
https://github.com/ydb-platform/ydb-embedded-ui/blob/main/src/containers/Tenant/utils/schemaQueryTemplates.ts
