### ISSUE TITLE
to think about and come up with an idea about fitting advanced storage info

### ISSUE THREAD

**Issue by adameat** [ydb-platform/ydb-embedded-ui#1037]
from there:
![image](https://github.com/user-attachments/assets/e55e80f5-b3f6-4d89-ba16-07ff0bbce33b)

to here:
![image](https://github.com/user-attachments/assets/17401008-b987-46bf-ad01-08fac5b686fc)

advanced storage view is hidden by default, the switch is only available for Monitoring users.

**Comment by artemmufazalov** [comment]
Agreed to implement this solution:

![Image](https://github.com/user-attachments/assets/88e97b59-8fdf-4aa4-86fd-6eeeb7ebeb95)
