### ISSUE TITLE
improve tablet page

### ISSUE THREAD

**Issue by adameat** [ydb-platform/ydb-embedded-ui#1042]
talking about this page:
![image](https://github.com/user-attachments/assets/1cdd0783-2da6-4b1a-8879-227476d084bc)

1. all tabletinfo calls should be with database parameter.
2. print tablet type and number in big letters in the beginning of the page.
3. get additional information from hive using this handler (for Monitoring+ users only):
    /tablets/app?TabletID=72075186224037895&page=TabletInfo&tablet=72075186224043741
    display information about bound channels and storage info
4. make shortcats to this hyperlinks (for Monitoring+ users only):
    ![image](https://github.com/user-attachments/assets/77afe014-eb3d-4b43-bee4-5cb057e417a8)
    we need: App, Counters, Executor DB Internals, State Storage

**Comment by adameat** [comment]
and change design of the page to match vdisk and pdisk pages

**Comment by adameat** [comment]
about hive:

![image](https://github.com/user-attachments/assets/2399cdac-483f-40da-b4ea-82b0cf3e9245)

we need to show every channel of the tablet and it storage configuration

![image](https://github.com/user-attachments/assets/ed865937-dc14-45f9-bd95-b933b18f4b2b)

and history of storage (for every channel)

I suggest do combine these two objects and show cumulative storage information (like a table maybe)

**Comment by Raubzeug** [comment]
Desided to organize additional info as collapsible table:
Columns: Channel, StoragePoolName (from BoundChannels), GroupId, FromGeneration, Timestamp
Visible row - the last entry from TableStorageInfo.Channels array. The rest of reversed TableStorageInfo.Channels are collapsed by default.
