### ISSUE TITLE
show disconnect time of disconnected node

### ISSUE THREAD

**Issue by adameat** [ydb-platform/ydb-embedded-ui#1065]
the idea is to show disconnect time as negative up time

![image_2024-07-25_16-24-08](https://github.com/user-attachments/assets/517afe2e-40c2-4c97-94b4-3e36781f1da5)

![image](https://github.com/user-attachments/assets/6d2b3462-19da-4433-b86a-1e81ef494393)

**Comment by antonkovalenko** [comment]
#1067 

Format of DisconnectTime might be changed from us to ms

**Comment by adameat** [comment]
current example of nodes (one disconnected and another is not):

![image](https://github.com/user-attachments/assets/29f7c22c-9a82-4395-baad-e25670451430)
