### ISSUE TITLE
Enable autorefresh for paginated tables

### ISSUE THREAD

**Issue by artemmufazalov** [ydb-platform/ydb-embedded-ui#1070]
Enable autorefresh and make possible manual refresh for paginated tables on Nodes and Storage tabs

**Comment by antonkovalenko** [comment]
Cluster / Nodes tab is not working at all

https://nda.ya.ru/t/P9NaG6MK77qYKb

**Comment by astandrik** [comment]
> Cluster / Nodes tab is not working at all
> 
> https://nda.ya.ru/t/P9NaG6MK77qYKb

Problem in Safari

will be fixed here https://github.com/ydb-platform/ydb-embedded-ui/issues/1223
