### ISSUE TITLE
pdisk page – add decommission control

### ISSUE THREAD

**Issue by antonkovalenko** [ydb-platform/ydb-embedded-ui#1092]
### Design drafts

Could be found at YCDESIGN-7572

### What to do

On a PDISK page decommission status must be displayed. 

![Image](https://github.com/user-attachments/assets/c367f859-b6dc-4126-aece-fcc8ad78c797)

As a user I want to click on decommision status to change it
if pdisk is any other state than NONE, status must be dispayed near PDISKID

![Image](https://github.com/user-attachments/assets/941aa7dc-c471-4f56-9351-8409aa905a73)

When I change decommission status confirmation request dialog must be displayed

![Image](https://github.com/user-attachments/assets/fa4825d7-1ee2-4f62-a45b-4f94d9e706a4)

**Comment by artemmufazalov** [comment]
Checkbox will be added here: https://github.com/ydb-platform/ydb-embedded-ui/issues/1207
