### ISSUE TITLE
Display all types of keys as plain text

### ISSUE THREAD

**Issue by antonkovalenko** [ydb-platform/ydb-embedded-ui#1116]
### Left schema tab

1. Remove Key column
2. By default display columns sorted by their appearence in the primary key
3. Display message above the table: **Primary key** col1, col2.
4. For column tables display message **Partitioning key** col1, col2 after primary key message

### Diagnostics (right) schema tab

1. Remove Key column
2. By default display columns sorted by their appearence in the primary key
3. Display message above the table: **Primary key** col1, col2.
4. For column tables display message **Partitioning key** col1, col2 after primary key message

**Comment by astandrik** [comment]
https://www.figma.com/design/bNbecZuPFDDrJ7ghaXZ2Fe/YDB-—-Tickets?node-id=2163-46560&t=uet4rej7PfWvUlKv-0
