### ISSUE TITLE
switch storage groups to use new handler storage/groups

### ISSUE THREAD

**Issue by adameat** [ydb-platform/ydb-embedded-ui#1125]
it's better to start with version 2 of storage/groups

and we expect to switch using viewer/capabilities only
```
~/work/ydb/ydb/apps$ curl -s "http://localhost:8766/viewer/capabilities" | jq . | grep storage/groups
    "/storage/groups": 2,
~/work/ydb/ydb/apps$
```

**Comment by artemmufazalov** [comment]
It was fixed here: https://github.com/ydb-platform/ydb-embedded-ui/pull/1225

Similar issue: https://github.com/ydb-platform/ydb-embedded-ui/issues/1160
