### ISSUE TITLE
Group and vdisk space utilization mode switch

### ISSUE THREAD

**Issue by antonkovalenko** [ydb-platform/ydb-embedded-ui#1158]
Add new option to Application settings  - "Use physical space utilization for groups"
When enabled groups and vdisk utilization must be calculated based on pdisk free space.
Every vidisk on pdisk has same ratio as pdisk

**Comment by artemmufazalov** [comment]
We added Disk Space column to Storage groups and nodes tables, it can be turned on with table columns setup control
