### ISSUE TITLE
Render per component memory consumption

### ISSUE THREAD

**Issue by kunga** [ydb-platform/ydb-embedded-ui#1177]
We want to show memory consumption for both cluster and individual nodes grouped by component

It may look like:

![telegram-cloud-document-2-5330471687588697304](https://github.com/user-attachments/assets/73f5a82d-d5e2-4f0a-9317-a6ea64d6cc71)

Currently we have only total YDB process memory used and caches consumption:

![image](https://github.com/user-attachments/assets/2e877fbd-2419-4849-9750-8ad9cda03d9f)

Currently available metrics for rendering can be found [here](https://github.com/ydb-platform/ydb/blob/main/ydb/core/protos/memory_stats.proto) and are reported to the node whiteboard:
- `ExternalConsumption` - the amount of memory that is consumed outside of YDB process (when there is no `CGroupLimit`)
- `AllocatorCachesMemory` - the amount of memory that has been released but not yet returned to the operating system
- `SharedCacheConsumption` / `SharedCacheLimit` - the shared cache consumption and limit
- `MemTableConsumption` / `MemTableLimit` - the mem table consumption and limit
- `QueryExecutionConsumption` / `QueryExecutionLimit` - the query execution consumption and limit

Total consumed memory is equal to ~`AllocatedMemory`~ `AnonRss`, total process available memory is `HardLimit` (may be equal to `CGroupLimit`, `MemAvailable`, or taken from configuration)

New components' metrics are likely to be added later

Related documentation is available [here](https://ydb.tech/docs/en/deploy/configuration/config#memory-controller)

**Comment by astandrik** [comment]
@kunga @adameat 

Please take a look at prototype with mocked data [Stand](https://nda.ya.ru/t/xbkRJynb79Npch)

Give a feedback on what need to be (conceptually) refined

<img width="587" alt="image" src="https://github.com/user-attachments/assets/586e1c0a-284e-476f-a3e3-cc960719624c">

**Comment by kunga** [comment]
lgtm
