### ISSUE TITLE
Empty explain plan table

### ISSUE THREAD

**Issue by artemmufazalov** [ydb-platform/ydb-embedded-ui#1179]
If there is no explain plan, some stub should be displayed, but not empty table

Result for `execute-script`:

<img width="1200" alt="Screenshot 2024-08-16 at 17 04 54" src="https://github.com/user-attachments/assets/60d11366-e22e-44d6-819e-5c51290ec367">

**Comment by antonkovalenko** [comment]
@Raubzeug please add small fix

**Comment by Raubzeug** [comment]
Checked. It's already fixed.
