### ISSUE TITLE
Add absolute time timestamp in addition to uptime

### ISSUE THREAD

**Issue by kunga** [ydb-platform/ydb-embedded-ui#1200]
When resolving an incident it's impossible to match relative uptime to any metric dashboards

#### Tablets uptime

![image](https://github.com/user-attachments/assets/6c473c41-de06-44fb-9a52-9937b0e8e990)

![image](https://github.com/user-attachments/assets/5dd2d7a5-8693-48d7-869a-5ffd35bb107d)

#### Host uptime

![image](https://github.com/user-attachments/assets/d8e7c865-24b4-42de-b674-52c5913aa4ae)

**Comment by antonkovalenko** [comment]
@kunga would it be better to see absolutely time of tablet or node start?

**Comment by antonkovalenko** [comment]
Display tooltip over uptime value with absolute time in user's local timezone. with zone code.

**Comment by kunga** [comment]
> @kunga would it be better to see absolutely time of tablet or node start?

The problem should be solved for both tablets and nodes (if that what you've asked)

**Comment by antonkovalenko** [comment]
It is better to them together #1065
