### ISSUE TITLE
Sort storage groups by their level of degradation

### ISSUE THREAD

**Issue by kunga** [ydb-platform/ydb-embedded-ui#1202]
Now there is two problems:

- default tab is `All` groups tab
- even if I click on the `Degraded` tab, groups aren't sorted by their missing count

I propose to always sort groups by their missing count first on both tabs, and definitely when I switch to `Degraded` tab

So **every time I switch to the `Degraded` tab it should use sort order by missing count, not my previous used one**

https://st.yandex-team.ru/CLOUDDUTY-29843#66c66125fb0016627709e9f4

**Comment by antonkovalenko** [comment]
Grouping was added. Hope it solves your problem?
<img width="1315" alt="image" src="https://github.com/user-attachments/assets/675b9728-267d-42f4-bdff-d5ea98d8e104">

@kunga

**Comment by kunga** [comment]
It wasn't obvious that I have to picked Goup by: State, but whatever
