### ISSUE TITLE
Show stable node name in list of nodes

### ISSUE THREAD

**Issue by pixcc** [ydb-platform/ydb-embedded-ui#1205]
On cloud clusters, `enable_stable_node_names` is enabled to limit the growth of stored metrics in time series monitoring. On such clusters, nodes have stable names in addition to hostname, which are displayed in monitoring and identify the node within the tenant. These stable names need to be shown in the embedded UI and be searchable, so that it is easy to match data from monitoring with nodes from the embedded UI.

If a node has such a stable name, it is returned from the `/json/nodes` endpoint in the `NodeName` field.

**Comment by antonkovalenko** [comment]
will be done when https://github.com/ydb-platform/ydb-embedded-ui/issues/1216 is committed

**Comment by antonkovalenko** [comment]
Artem adds new column to a column selector
