### ISSUE TITLE
show paths and shards usage

### ISSUE THREAD

**Issue by adameat** [ydb-platform/ydb-embedded-ui#1213]
currently, for a database, we show number of paths and shards in it.

![image](https://github.com/user-attachments/assets/21eab673-9873-4ef9-96a4-23abd32f592b)

but most of the time we have limits for these numbers:

![image](https://github.com/user-attachments/assets/004f982c-c5c6-4fc3-bcfd-2f73c76d75f1)

I think it would be nice to show these limits in small overview area.

**Comment by JuliaMinullina** [comment]
задачу согласовали, макеты: https://nda.ya.ru/t/9k4qytsD77xRFn
