### ISSUE TITLE
redesign database info page

### ISSUE THREAD

**Issue by adameat** [ydb-platform/ydb-embedded-ui#1214]
currently we have this situation:

![image](https://github.com/user-attachments/assets/e2027a69-7445-4a98-8e42-a9b3c7962141)

the problems are:
1. users can't understand values in the cards in the upper area. they want to know capacity of a database in terms of physical resources (total cores, total gigabytes and so on). it should be in a simple terms.
2. they don't understand that this cards are clickable and can give better information about selected resource.

a while ago we came up with idea of circle bars in the cards, but it wasn't the good time for that.
now I think we could try again.
I made some sketch, but it's just an idea...

![image](https://github.com/user-attachments/assets/cbf32bba-46f0-400b-ae6c-d7b1a882f7ed)

**Comment by artemmufazalov** [comment]
Circle progress bars, that we had before
![CPU с пулами](https://github.com/user-attachments/assets/41bf4e2a-e07f-437c-815d-b54e6d03c0cd)

**Comment by JuliaMinullina** [comment]
https://nda.ya.ru/t/VFaCKf3O783BoT
needs review @adameat
