### ISSUE TITLE
display timeouted and running queries on the queries tab

### ISSUE THREAD

**Issue by antonkovalenko** [ydb-platform/ydb-embedded-ui#1232]
Inspired by YCDESIGN-7944
- [ ] display timeouted queries on diagnostics page for a database
- [ ] [display currently running queries](https://github.com/ydb-platform/ydb-embedded-ui/issues/1020) on a queries tab
- [ ] rename top queries tab to queries and display timeouted queries
- [ ] add filter to queries tab so that user could filter just timeouted queries
- [ ] display a red dot over queries tab if there were timeouted queries during last 15 minutes

**Comment by JuliaMinullina** [comment]
https://nda.ya.ru/t/Eaou-NRT783MCX
needs review @antonkovalenko @adameat

**Comment by antonkovalenko** [comment]
> https://nda.ya.ru/t/Eaou-NRT783MCX needs review @antonkovalenko @adameat

Okay, as we have discussed:

1. We cannot display timeouted now. so switch will have only two options
2. Running must not date datepicker
