### ISSUE TITLE
As a cluster administrator I want to group entities by different params

### ISSUE THREAD

**Issue by antonkovalenko** [ydb-platform/ydb-embedded-ui#1241]
AS a cluster admin I want to see how many groups on the cluster has -2 devices. Or how many nodes are in datacenter X

Or how many nodes have pdisks with usage from 60%  to 70%.

Basicaly I want to apply this grouping to following views:

* databases 
* nodes
* groups

**Comment by JuliaMinullina** [comment]
needs review @antonkovalenko @adameat https://nda.ya.ru/t/MDAwdVT978D6Xh

**Comment by adameat** [comment]
> needs review @antonkovalenko @adameat https://nda.ya.ru/t/MDAwdVT978D6Xh

looks fine to me
