### ISSUE TITLE
`PaginatedTable` need time to process a lot of chunks

### ISSUE THREAD

**Issue by artemmufazalov** [ydb-platform/ydb-embedded-ui#1250]
When table has a lot of chunks (400+), it has freezes on initial load and when switching tabs

How to reproduce:
1) Open Nodes / Storage tab, with entities count 20_000+
2) Open another tab
3) Go back to Nodes / Storage tab - there will be 1 chunk for some time

https://nda.ya.ru/t/nc7HSDwZ77z6d6

**Comment by antonkovalenko** [comment]
fixed by [#1472](https://github.com/ydb-platform/ydb-embedded-ui/issues/1472)
