### ISSUE TITLE
Cluster overview

### ISSUE THREAD

**Issue by Raubzeug** [ydb-platform/ydb-embedded-ui#1257]
1) Information about nodes quantity in datacenter. For now we have only labels with DC name. We may add quantity as `SOME: 15` or depict it as progress bar (see versions progress bar as an example).
2) Information about nodes status (`Green: 10, Red: 1, Gray: 5`). Progress bar or smth else?

<img width="889" alt="Screenshot 2024-09-05 at 12 16 37" src="https://github.com/user-attachments/assets/e04bb66e-a339-4c32-b5b4-bd6f7d85806a">

<img width="1028" alt="Screenshot 2024-09-05 at 12 14 13" src="https://github.com/user-attachments/assets/03465300-4d2d-4a46-b672-8569958e62b6">

**Comment by Raubzeug** [comment]
For now it looks like:

<img width="863" alt="Screenshot 2024-09-16 at 15 26 40" src="https://github.com/user-attachments/assets/6fc59dac-09e2-4cf5-a3cd-396e7fe3da2a">

**Comment by antonkovalenko** [comment]
1. frequent question: how many groups to create do we have?

**Comment by JuliaMinullina** [comment]
@antonkovalenko @Raubzeug @adameat needs review https://nda.ya.ru/t/X_0HCBcb78KaS7

**Comment by Raubzeug** [comment]
@JuliaMinullina it seems we don't have info about nodes states in the context of datacenters. I.e. we have information about overall nodes quantity in dcs (FOO: 10, BAR: 15) and information about overall quantity nodes with distinct state (red: 10, blue: 5).

**Comment by antonkovalenko** [comment]
Looks nice
I would choose v3 with dashboards
