### ISSUE TITLE
Add grouping to storage tab

### ISSUE THREAD

**Issue by antonkovalenko** [ydb-platform/ydb-embedded-ui#1302]
Implement design from [As a cluster administrator I want to group entities by different params](https://github.com/ydb-platform/ydb-embedded-ui/issues/1241)

* [x] #1365
* [ ] add grouping to Storage RDT table

**Comment by artemmufazalov** [comment]
Add grouping only for columns, that are in table

**Comment by artemmufazalov** [comment]
Decided to keep grouping only for `PaginatedTables`
