### ISSUE TITLE
[Paginated table] increase active chunks count

### ISSUE THREAD

**Issue by artemmufazalov** [ydb-platform/ydb-embedded-ui#1372]
`PaginatedTable` loads and renders 150% of parent container height. It's 2-3 chunks, 100-150 row. 

We need to increase this amount - 2 chunks up and down from the chunk in the viewport, to prevent loading rows on scroll.

1. Increase intersection margin - `DEFAULT_INTERSECTION_OBSERVER_MARGIN`
2. Tune `DEBOUNCE_TIMEOUT`, so it will be as low as possible, but at the same time no excessive data will be loaded on fast scroll
3. Add virtualization - load data, but do not render rows, until they are visible

**Comment by adameat** [comment]
@artemmufazalov don't you mind to close this issue?
