### ISSUE TITLE
Nodes list stops working on sort by uptime + scroll down

### ISSUE THREAD

**Issue by kunga** [ydb-platform/ydb-embedded-ui#1383]
Steps to reproduce:
- open database
- open nodes tab
- sort by uptime
- scroll fast down

List stops working

https://t.me/c/1483996811/13695

**Comment by artemmufazalov** [comment]
The reason: `PaginatedTable` `TableChunk` initially have very small width, so if the table scrolled to the right, `TableChunk` isn't viewed by `IntersectionObserver`, so chunk doesn't become active and data isn't loaded
