### ISSUE TITLE
show absent vdisk's as having average width (size) as the rest of present disks

### ISSUE THREAD

**Issue by adameat** [ydb-platform/ydb-embedded-ui#1433]
![image](https://github.com/user-attachments/assets/79a7b542-9179-4ecf-b85a-d14d5ae1c3e6)

**Comment by artemmufazalov** [comment]
@adameat 

Is what we expect here? All disks without `AllocatedSize` field have size equal to `VDISKS_CONTAINER_WIDTH / VDisks.length` (excluding spaces between disks)  

Normal space distribution and relative size:
![Screenshot 2024-10-21 at 14 26 37](https://github.com/user-attachments/assets/19f85331-9ad9-411f-89c6-ed275425a970)

Case where some VDisks have more `AllocatedSize`, than others:
![Screenshot 2024-10-21 at 14 26 50](https://github.com/user-attachments/assets/5fda28da-8b37-4a5b-bda2-b92baf1849f3)
