### ISSUE TITLE
describe a hotfix process and implement it

### ISSUE THREAD

**Issue by antonkovalenko** [ydb-platform/ydb-embedded-ui#1492]
Currently hotfixes are not described.

In this ticket it is required:

- write a description in project wiki as an article in a project wiki
- add tooling for the process
- make a talk on ui standup to discuss with the team

**Comment by artemmufazalov** [comment]
Instruction: https://github.com/ydb-platform/ydb-embedded-ui/wiki/Developer-Tips#making-a-hotfix-version
