### ISSUE TITLE
storage/nodes – group boundaries span way below content

### ISSUE THREAD

**Issue by antonkovalenko** [ydb-platform/ydb-embedded-ui#1530]
### Steps to reproduce 

1. Open Cluster / Storage tab for ydb ru
2. Switch to Nodes mode
3. Group by DC
4. Open KLG group
5. scroll down
6. notice that nodes list has come to an end, but the group boundary is not visible it looks like you can still scroll

![Image](https://github.com/user-attachments/assets/2cdd1438-f848-45de-8314-69c22bd17d36)

**Comment by astandrik** [comment]
will be fixed here https://github.com/ydb-platform/ydb-embedded-ui/issues/1472
