### ISSUE TITLE
Add to Embedded UI link to Plan2Svg converter

### ISSUE THREAD

**Issue by Hor911** [ydb-platform/ydb-embedded-ui#1543]
API was implemented here:

https://github.com/ydb-platform/ydb/pull/10368

Input: Plan in JSON format as returned by server (for stats mode FULL+)
Output: Image in SVG format

**Comment by antonkovalenko** [comment]
- add setting to a query setting dialog (generate query execution smth by svg)
- add link after query execution where tracing link is displayed

**Comment by Hor911** [comment]
> * add setting to a query setting dialog (generate query execution smth by svg)
> * add link after query execution where tracing link is displayed

SVG is created by demand (after click). There is no need in any settings, we can just always add link.
