### ISSUE TITLE
Sort all system folder either on top or bottom

### ISSUE THREAD

**Issue by kungasc** [ydb-platform/ydb-embedded-ui#1576]
Now folders that starts with dot symbol a chaotically placed in top AND in bottom, something one should be picked

![image](https://github.com/user-attachments/assets/8a0a1865-56af-4937-97ac-6e7dd46e7f8d)

![image](https://github.com/user-attachments/assets/bae2cf9e-36e8-4460-b858-63ade2d05bfd)

**Comment by antonkovalenko** [comment]
will be fixed automatically by https://github.com/ydb-platform/ydb/issues/10150
