### ISSUE TITLE
replace network diagnostics page

### ISSUE THREAD

**Issue by adameat** [ydb-platform/ydb-embedded-ui#1602]
starting with version 13 of /viewer/nodes AND under experiment, turned off by default
display nodes table with the following columns:
1. ConnectStatus (default)
2. NodeId (default)
3. Host (default)
4. DC, Rack, Uptime, CPU, Pools (**turned off** by default)
5. Connections (default) example "13"
6. NetworkUtilization in 0..1 float value (default, NetworkUtilizationMin and NetworkUtilizationMax in popup) convert to percent, example "13%"
7. SendThroughput in bytes/sec (default) convert to mb/s, example "0.13 MBps"
8. ReceiveThroughput in bytes/sec (default) convert to mb/s, example "0.13 MBps"
9. PingTime in us (default, PingTimeMin and PingTimeMax in popup) convert to ms, example "1.3 ms" or "13 ms"
10. ClockSkew in us with sign (default, ClockSkewMin and ClockSkewMax in popup) convert to ms, example "-1.3 ms" or "+13 ms"

**Comment by artemmufazalov** [comment]
Table from Nodes tab - with pagination, autorefresh, required fields param to backend, table columns setup, etc.

Use only columns, described in this issue.

`Overall` status in `NodeHostWrapper` component should be replaced with `ConnectStatus`.

Grouping by `SystemStatus` should be replace with grouping by `ConnectStatus`, `NetworkUtilization`, `ClockSkew`, `PingTime` should be added, redundant columns should be removed

**Comment by artemmufazalov** [comment]
Network stats were added here: https://github.com/ydb-platform/ydb/pull/11344
