### ISSUE TITLE
Add Duration column to TopQueries

### ISSUE THREAD

**Issue by artemmufazalov** [ydb-platform/ydb-embedded-ui#609]
Add duration column, enable sorting. Display duration in ms, mention ms in column title - "Duration, ms". Data should be taken from top queries system table

**Comment by antonkovalenko** [comment]
Duration is [returned in usec](https://ydb.tech/docs/en/troubleshooting/system_views_db), which is not obviouos to learn from docs

so to display them in microsec, the value from the system table must be divided by 1k
