### ISSUE TITLE
Replace autorefresh with advanced control

### ISSUE THREAD

**Issue by artemmufazalov** [ydb-platform/ydb-embedded-ui#612]
There is a button that toggle autorefresh in Diagnostics. It's needed to add additional button to refresh current Diagnostics tab content. 

Possible solution - store fetch data functions added with `useAutofetcher` in autofetch class and trigger them on button click. Manual autorefresh should also postpone next passive autorefresh if it's enabled.

<img width="344" alt="Autorefresh" src="https://github.com/ydb-platform/ydb-embedded-ui/assets/67755036/a886e1d8-3a3e-43d2-b404-43154e6e911b">

**Comment by ValeraS** [comment]
What intervals should we use for automatic updates?

**Comment by antonkovalenko** [comment]
- 15s
- 1m
- 2m
- 5m
