### ISSUE TITLE
Optimise query results

### ISSUE THREAD

**Issue by artemmufazalov** [ydb-platform/ydb-embedded-ui#616]
Currently on very big datasets in results or with big request stats some use cases are very slow and could take up to **2-3 seconds** 😱. Big stats are quite a common thing for requests with multi schema.

Use cases:
1. Switching from History or Saved tab to Query tab if there are some results
2. Switching to results from stats and vice versa

What could be done:
1. Keep rendered elements on screen (for example with `display: none`), so they won't be calculated again. Applicable to result tables, stats, ast, explain plan and `Fullscreen` component
2. Optimise data calculations and rendering

Migrating `QueryEditor` files to TS is essential for this issue: https://github.com/ydb-platform/ydb-embedded-ui/issues/619

---

Inspired by: https://github.com/ydb-platform/ydb-embedded-ui/pull/595#discussion_r1403494080

**Comment by antonkovalenko** [comment]
@Raubzeug please link this one to a ticket about migration

**Comment by Raubzeug** [comment]
I've double checked the situation, and it still needs some improvements.
Huge tables are re-rendering every time we return to the tab with results (or switch to Fullscreen).

**Comment by antonkovalenko** [comment]
@Raubzeug please add a screencast

**Comment by artemmufazalov** [comment]
### Query result table optimization

With `dynamicRenderType: 'variable'` and `dynamicItemSizeGetter` table renders all its cells, it causes performance issues on big tables.

Rendering of a query result table with 100 000 rows.

With `dynamicRenderType: 'variable'` and `dynamicItemSizeGetter`:
![100_000 before](https://github.com/user-attachments/assets/8ca2b471-f76f-4a40-b3f8-220cea64318e)

With `'uniform'` rendering:
![100_000 after](https://github.com/user-attachments/assets/2ad90a36-64d4-4396-8648-1b6b939ae9ea)
