### ISSUE TITLE
VDisk page

### ISSUE THREAD

**Issue by artemmufazalov** [ydb-platform/ydb-embedded-ui#617]
All VDisk links should lead to this page.

Node Structure tab remains as it is.

On this page we should display VDisks info and info about related nodes and groups. Reference - VDisk info popup on Node Structure tab.

VDisk Developer UI link should be present.

Below VDIsk info there should be Storage table with groups / nodes radio button, filtered by VDisk id.

**Comment by StekPerepolnen** [comment]
evict query 

```
:8765/tablets/app?TabletID=72057594037932033&exec=1
Content-Type: application/json
{
  "Command": {
    "ReassignGroupDisk": {
      "GroupId": 2181038080,
      "GroupGeneration": 2,
      "FailRealmIdx": 0,
      "FailDomainIdx": 0,
      "VDiskIdx": 0
    }
  }
}
```
72057594037932033 - is the const BSC tabletID
all ids could be obtained by /storage handler
