### ISSUE TITLE
PDIsk page

### ISSUE THREAD

**Issue by artemmufazalov** [ydb-platform/ydb-embedded-ui#618]
Add new link from pdisk structure view

Node Structure tab remains as it is.

On this page we should display PDisks info and info about related groups. Reference - PDisk info on Node Structure tab.

PDisk Developer UI link should be present.

Below PDIsk info there should be Storage table with groups

Design: https://nda.ya.ru/t/NxdRowXN74sxmC

**Comment by StekPerepolnen** [comment]
using pdisk restart format
`/actors/pdisks/{pad9(PDiskID)}?restartPDisk=`
using pdisk restart example
`/actors/pdisks/pdisk000000001?restartPDisk=`

**Comment by artemmufazalov** [comment]
> using pdisk restart example (`PDiskID`=0001) `:8765/actors/pdisks/pdisk000000001?restartPDisk=`

Is this a `POST` or `GET` requet?

Could you also give an example of request to evict all PDisk VDisks?

![Image](https://github.com/ydb-platform/ydb-embedded-ui/assets/67755036/6e72fcc4-464a-44ca-9aae-389692e00dc0)

**Comment by StekPerepolnen** [comment]
> > using pdisk restart example (`PDiskID`=0001) `:8765/actors/pdisks/pdisk000000001?restartPDisk=`
> 
> Is this a `POST` or `GET` requet?
> 
> Could you also give an example of request to evict all PDisk VDisks?
> 
> ![Image](https://private-user-images.githubusercontent.com/67755036/310070565-6e72fcc4-464a-44ca-9aae-389692e00dc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MjQ2NDEsIm5iZiI6MTcwOTcyNDM0MSwicGF0aCI6Ii82Nzc1NTAzNi8zMTAwNzA1NjUtNmU3MmZjYzQtNDY0YS00NGNhLTlhYWUtMzg5NjkyZTAwZGMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDExMjU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjOTZiYmE3ZDdiZGUxYjFlNDQ0ZmQ1NGNjYzc1NjIxY2YzMWMyOWQ3ZjZmNWI0NGJjM2VjM2ZlMDZkZjBkZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WY0anLvQq541-H9lSskNsPzLp1amnv46qo60PPWsIUQ)

POST
