### ISSUE TITLE
Move infos about cluster to a cluster tab

### ISSUE THREAD

**Issue by antonkovalenko** [ydb-platform/ydb-embedded-ui#623]
Currently there are several tabs on a cluster page:
* Databases
* Nodes
* Storage
* Version

Competitors have cluster info on a special tab.
It seemed to us more expected way to organize cluster parameters

Let's add a new tab **Overview** to the left of Databases
Move all the fields that are displayed currenty about cluster as they are

Remove special control and cluster info from the top section of the page
Leave only cluster name and HC status

**Comment by ValeraS** [comment]
Should we keep the "Databases" tab as initial active tab or change it to "Overview"?

**Comment by adameat** [comment]
> Should we keep the "Databases" tab as initial active tab or change it to "Overview"?

good question. how about we change default tab to "overview" (because it's a first tab on the page), but will remember selected tab and use that tab on the next load?

**Comment by antonkovalenko** [comment]
I was too slow (
Why should we change the default view of a cluster?

1. None have ever asked
2. None have ever complained
3. People don't like additional clicks
4. almost nodoby needs info about cluster and most of the users go to either developer ui or database page. 
5. let's not change the default tab

**Comment by adameat** [comment]
> I was too slow ( Why should we change the default view of a cluster?

don't be slow next time :)
sorry, but nobody makes default tab in the middle of a tab group. it doesn't make sense.
as a compromise I suggested to rember last opened tab, it should address the concerns you pointed out.
