### ISSUE TITLE
Request Hot Keys Sampling on empty response

### ISSUE THREAD

**Issue by antonkovalenko** [ydb-platform/ydb-embedded-ui#624]
To draw HotKeys tab for a table `viewer/json/hotkeys` knob is requested. When response is empty, it must be called again with parameter `enable_sampling=true`.

Sampling will take aprox 5 seconds.  Let's write a message `Please wait for 5 seconds while we looking for the hot keys"

After 5 seconds let's request `viewer/json/hotkeys` again.

If it's still empty let's write "No hot keys".

In autorefresh mode no `enable_sampling=true` parameter is required.

**Comment by artemmufazalov** [comment]
Currently, we have Hot Keys tab for column tables. However, it doesn't supported properly neither on frontend, nor on a backend

Backend code:
https://github.com/ydb-platform/ydb/blob/main/ydb/core/viewer/json_hotkeys.h#L84

**Comment by artemmufazalov** [comment]
> I will disable this tab for column tables, if we want to add it later, we need to add support on backend

Update: data from column tables rarely requested by certain keys, more often it is range operations. So this tab is not really applicable there

**Comment by antonkovalenko** [comment]
Thanks

С уважением, Антон Коваленко
тел: +7 926 214 77 82
telegram: kovalad@
