### ISSUE TITLE
Charts on Database info page

### ISSUE THREAD

**Issue by antonkovalenko** [ydb-platform/ydb-embedded-ui#625]
Display charts on first entry at Database info tab

1. Number of API requests per second
1. Transaction Latency. Server latency for all tx types - several lines for following percentiles: p50, p75, p90, p99

When CPU toggle is pressed let's show the following chart. It must be as wide as all for toggles and displayed above all other infos.

1. CPU consumption
   * cores, pcs (database compute nodes total)

When storage is toggled

1. Database size
   * usage, bytes 

When memory is toggled

1. Memory consumtion
   * usage bytes

Timerange selection control must be displayed ab above all charts. Buttons like in Monitoring.

* 30m
* 1h 
* 1d
* 1w

**Comment by adameat** [comment]
the handler called "/viewer/json/render". it replicates Graphite protocol, so it's possible to add /viewer/json as Graphite data source to Grafana. you can read more about the protocol here https://graphite.readthedocs.io/en/latest/render_api.html
the simple example could be seen on this screenshot:
![image](https://github.com/ydb-platform/ydb-embedded-ui/assets/34044711/44b14e83-15b3-4eaf-bc9e-df5535642367)
