### ISSUE TITLE
Draw 2nd thin circle in diagnostics DB page

### ISSUE THREAD

**Issue by antonkovalenko** [ydb-platform/ydb-embedded-ui#626]
External circle displays total metric for the database.
Internal circle – max value of a metric from a list of objects

1. CPU - internal circle displays max of (user pool consumption, system pool consumption)

2. Storage – internal circle displays max consumption of all database groups

3. Memory – max memory consumption of all database nodes

In the center of the circle total absolute consumption must be displayed and utilisation (usage / limit, %)

Every toggle must have a tooltip with explanation for external and internal circles

**Comment by artemmufazalov** [comment]
Currently we agreed only on a border for diagnostics circles - https://github.com/ydb-platform/ydb-embedded-ui/issues/627

As for the second circle with additional metric, it's a question we should discuss.
