### ISSUE TITLE
Display base64 query response as string

### ISSUE THREAD

**Issue by artemmufazalov** [ydb-platform/ydb-embedded-ui#639]
To do it, special flag should be passed to `viewer/json/query` api call.

Additional setting should be added, this flag should be passed only if setting is active

---

Param name: `base64`, by default true (strings are returned encoded). It should be 'false' to receive decoded strings in response.

We need to discuss, whether this flag could be added to General Settings section, since it is present only on latest ydb versions.

**Comment by antonkovalenko** [comment]
the aforementioned flag was added at https://github.com/ydb-platform/ydb/pull/647

**Comment by vovaspace** [comment]
> We need to discuss, whether this flag could be added to General Settings section, since it is present only on latest ydb versions.

Can we add this flag without any conditions, since newer versions of UI will be embedded into newer versions of ydb?

**Comment by artemmufazalov** [comment]
> Can we add this flag without any conditions, since newer versions of UI will be embedded into newer versions of ydb?

1. After some discussions we decided not to turn it on by default, but add as an option for the user

1. Embedded version correlates with specific ydb version. However, it's also used as a package in multi-cluster view, where we could have clusters with different ydb versions, including old ones, so it should work on all that versions

That's why the question, where to add this setting, has arised. It seems, currently it better fits experiments section

**Comment by vovaspace** [comment]
For multi-cluster UI I suggest just add a description under the setting title like "it will work starting from x.x.x version".

**Comment by artemmufazalov** [comment]
> For multi-cluster UI I suggest just add a description under the setting title like "it will work starting from x.x.x version".

If there is ydb version with this feature, this could be a solution

**Comment by vovaspace** [comment]
How is it better to formulate the flag title? “Disable base64 encoding” with default `false` value or “Enable …” with default `true` value?

As I see, all of other flags have default `false` values. But in my opinion, disabled base64 is like “normal” behavior and the flag should be about enabling.

**Comment by antonkovalenko** [comment]
Let's name the flag 'Display binary data in plain text', set default to true, it will BREAK current behaviours.
Place the flag to Settings sections
