### ISSUE TITLE
automatically build embedded ui into ydbd

### ISSUE THREAD

**Issue by antonkovalenko** [ydb-platform/ydb-embedded-ui#654]
Agreed to automate step-by-step instruction --to be published on wiki-- that clones embedded ui repo, runs npm build command
publishes resources to ydbd build process 
and runs e2e tests for UI

and then commits resources into ydb repo on success

**Comment by vovaspace** [comment]
`ydb` PR — https://github.com/ydb-platform/ydb/pull/1321,
`ydb-embedded-ui` PR — https://github.com/ydb-platform/ydb-embedded-ui/pull/672.

### How it works

- During the `ydb-embedded-ui` release flow, the UI is built into `embedded-ui.zip` and uploaded to a GitHub release;
- `embedded_ui_refresh` event is triggered in `ydb` repository;
- A flow is launched in `ydb` repository, which downloads `embedded-ui.zip` release asset, places files and opens a PR.
