### ISSUE TITLE
Vdisk usage bar – white letters on yellow background are hard to read

### ISSUE THREAD

**Issue by antonkovalenko** [ydb-platform/ydb-embedded-ui#658]
Low contrast
White on yellow looks unnatural

**Comment by antonkovalenko** [comment]
![Image](https://github.com/ydb-platform/ydb-embedded-ui/assets/692649/ea2a6f7f-5742-4691-8c44-8b24fcd616c0)

**Comment by artemmufazalov** [comment]
Is that better? Changed text color in light mode, added bar opacity in dark mode, added background to both themes.

Light before:
![Screen Shot 2024-02-12 at 17 36 42](https://github.com/ydb-platform/ydb-embedded-ui/assets/67755036/bc18db56-721f-42c6-903d-93ae201de9b4)

Light after:
![Screen Shot 2024-02-12 at 17 35 55](https://github.com/ydb-platform/ydb-embedded-ui/assets/67755036/825f818e-9836-4006-a8af-e04c9f719ff4)

Dark before:
![Screen Shot 2024-02-12 at 17 28 58](https://github.com/ydb-platform/ydb-embedded-ui/assets/67755036/812f7c94-fb81-4ca8-949e-ec581ee0840b)

Dark after:
![Screen Shot 2024-02-12 at 17 36 01](https://github.com/ydb-platform/ydb-embedded-ui/assets/67755036/00210562-2acb-4dcb-a602-c3ea84b05ed3)

Example with VDisk progress bar:
![Screen Shot 2024-02-12 at 17 35 36](https://github.com/ydb-platform/ydb-embedded-ui/assets/67755036/f8005575-acd3-4037-a242-1ea316e4d7e5)

![Screen Shot 2024-02-12 at 17 38 41](https://github.com/ydb-platform/ydb-embedded-ui/assets/67755036/de1a5d49-0738-46b3-abdc-1442790d8f0c)

**Comment by antonkovalenko** [comment]
Looks way better to me )
