### ISSUE TITLE
Not obvious CPU card in database diagnostics

### ISSUE THREAD

**Issue by artemmufazalov** [ydb-platform/ydb-embedded-ui#673]
### Improve after UX-tests

1. Replace circle diagrams with horizontal bars
2. CPU – use only three (IC, User, System) thread pools
3. Display absolute consumption and limit on the bar, as it's done in other places. With units
4. Display red and yellow (and orange?) icons. Example below uses exclamation sign in a triangle. Every level must have a sign (except when it's okay)
5. Memory must be displayed using bar as well. I'm sure we will add more bars later for memory, but let's start with the one
6. Display switch title in hyperlink style so it would be obviously clickable

DB diagnostics CPU card shows max cpu usage among user and system pools. It's not obvious, metric "used cores / total db cores" is expected here

https://github.com/ydb-platform/ydb-embedded-ui/blob/main/src/store/reducers/tenants/utils.ts#L46

![Screen Shot 2024-01-26 at 15 08 20](https://github.com/ydb-platform/ydb-embedded-ui/assets/67755036/98c3e0f9-b3e9-4074-8ca7-16e70031e876)

**Comment by antonkovalenko** [comment]
I'm going to run several experiments causing problems this widget is supposed to highlight.
Let's discuss the results and decided then

**Comment by antonkovalenko** [comment]
Proposal after experiments and discussion with Oleg

1. Remove number of cores indication
2. Leave percentage utilisation for max of (user, system, ic) pools. Let's don't include utilisation of batch pool, since we can't remember a case when it helps
3. Add detailed CPU consumption infos when CPU toggle is pressed (below the charts). Detailed infos must include:
   * utilisation indicator (bar)
   * percentage
   * available cores
   * used cores
4. this page must have a link to the docs with explanation of thread pools and actor system configs.
    * https://ydb.tech/docs/en/deploy/configuration/config#actor-system

**Comment by artemmufazalov** [comment]
How it should look like? We have these pools indicators on Node page. Should it be something similar, but with additional progress bar with cores used?

<img width="900" alt="Screen Shot 2024-02-09 at 14 31 46" src="https://github.com/ydb-platform/ydb-embedded-ui/assets/67755036/2ba2b241-556e-4691-97cb-5f2931c29b1d">

**Comment by artemmufazalov** [comment]
@antonkovalenko @adameat 

![Screen Shot 2024-02-15 at 17 50 27](https://github.com/ydb-platform/ydb-embedded-ui/assets/67755036/dc7e4ca4-3dd4-45d0-8d6c-7f7055b95d8b)

**Comment by artemmufazalov** [comment]
Another version:

![Screen Shot 2024-02-16 at 15 22 28](https://github.com/ydb-platform/ydb-embedded-ui/assets/67755036/4c54dad4-6661-407a-8ba5-7f38c237070f)

**Comment by antonkovalenko** [comment]
So, we did an UX-test with users from our chat and random people from a service that does such researches.
Several options of how to display diagnostics about consumption were tested.
After internal discussion we have chosen the one with horizontal bars



![Image](https://github.com/ydb-platform/ydb-embedded-ui/assets/692649/2f0a61dc-9e9d-4d5b-855c-426417889f3f)



![Image](https://github.com/ydb-platform/ydb-embedded-ui/assets/692649/dbfc0881-e974-45cd-b7d1-e8e5a1c197df)

Let's redo all circles to horizontal bars, if users like them bars.

**Comment by artemmufazalov** [comment]
@antonkovalenko 

Version with numbers on Progress bars. We don't have current and limit values for pools, so there are just percents.

I used our Progress bars, that are used everywhere in the UI. Also I used the same icons, that we have to HC.

How is it?

![Image](https://github.com/ydb-platform/ydb-embedded-ui/assets/67755036/2e983c25-ff94-4a3e-97ad-ca92322484ab)

**Comment by antonkovalenko** [comment]
> @antonkovalenko
> 
> Version with numbers on Progress bars. We don't have current and limit values for pools, so there are just percents.

Okay.
But it sounds weird 
@adameat don't we really have core used / core limit in absolute numbers?

> 
> I used our Progress bars, that are used everywhere in the UI. Also I used the same icons, that we have to HC.
> 
> How is it?
> 


Nice!
1. I don't like icons. The ones used at mockups were way better. With exclamation sign and triangles. Can we use them?
2. Bars without captions look orphaned. Let's discuss tomorrow how we will display different storage types and what lable is appropriate for memory

**Comment by adameat** [comment]
> > @antonkovalenko
> > Version with numbers on Progress bars. We don't have current and limit values for pools, so there are just percents.
> 
> Okay. But it sounds weird @adameat don't we really have core used / core limit in absolute numbers?
> 
of course we have.
