### ISSUE TITLE
Too large URL

### ISSUE THREAD

**Issue by pixcc** [ydb-platform/ydb-embedded-ui#700]
When I click on some system tablet in the list of all databases, I get `414 Request-URI Too Large`.

It has many storage nodes that are added to the URL like [/tabletsFilters?nodeIds[0]=1&nodeIds[1]=2](url) ...

**Comment by antonkovalenko** [comment]
- get rid of nodeids

**Comment by antonkovalenko** [comment]
closed due to tablets being removed from the list of databases

**Comment by antonkovalenko** [comment]
this page is removed from UI
