### ISSUE TITLE
Login with password gets stuck

### ISSUE THREAD

**Issue by blinkov** [ydb-platform/ydb-embedded-ui#703]
![photo_2024-02-05 22 01 53](https://github.com/ydb-platform/ydb-embedded-ui/assets/623861/2d7164d5-a04b-46d8-a657-8c775f66b3d9)
Two people have independently reproduced this on YDB v23.3.13 and v23.3.17 by following these instructions: https://github.com/ydb-platform/ydb/pull/1355

**Comment by antonkovalenko** [comment]
Could you please provide us with headers and response screenshots or .har file maybe?

**Comment by adameat** [comment]
it's a known issue. it was fixed in a new release (24-1).

**Comment by blinkov** [comment]
> it's a known issue. it was fixed in a new release (24-1).

Yep, I've just tried again with a binary built from the recent source code and it works fine, thanks!
