### ISSUE TITLE
Use database storage quota in diagnostics

### ISSUE THREAD

**Issue by antonkovalenko** [ydb-platform/ydb-embedded-ui#718]
Describe request for a database in some configurations might return attrubutes with storage quota. It limits the size of tablet data that could be saved in this database.

When datasize exceeds or equals to quota all write operations to the database are finished with error (out of space)

When `DatabaseQuotas.data_size_soft_quota` exists let's display storage panel based on tablet and topics size and DatabaseQuotas.data_size_soft_quota as a limit

**Comment by artemmufazalov** [comment]
Currently we use `data_size_hard_quota` for table storage limit. Should I replace it with `data_size_soft_quota`?

**Comment by antonkovalenko** [comment]
> Currently we use `data_size_hard_quota` for table storage limit. Should I replace it with `data_size_soft_quota`?

No, let's keep the hard limit.
