### ISSUE TITLE
🍷 Add Usage section to PDisk page

### ISSUE THREAD

**Issue by artemmufazalov** [ydb-platform/ydb-embedded-ui#760]
1. Add tabs under info overview
2. Move storage groups to one tab "storage"
3. Add tab "Consumption" or "Details" and display something like this 

![Image](https://github.com/ydb-platform/ydb-embedded-ui/assets/692649/284c6c10-1fc7-467e-8f42-86495c37d2bd)

**Comment by antonkovalenko** [comment]
final https://nda.ya.ru/t/sADYLLLd76PxXv
