### ISSUE TITLE
Indentify replication targets tables with a sign

### ISSUE THREAD

**Issue by antonkovalenko** [ydb-platform/ydb-embedded-ui#786]
Tables that receive changes from another database by means of async replicatoin are in read-only state.

Let's mark them with  a special ring. ~~It has to be an animated overlay on the standard table library~~

![Image](https://github.com/ydb-platform/ydb-embedded-ui/assets/692649/d7a67d4f-15f0-4b9d-909d-26cad063406d)

And also let's display this info on Info panel and overpanel as well.

@CyberROFL knows parameter that is returned in describe for such tables

describe for a table that is a replicated targert must contain attribute `__async_replica`

**Comment by CyberROFL** [comment]
https://github.com/ydb-platform/ydb/issues/3317

**Comment by artemmufazalov** [comment]
Decided to mark tables with labels in `Info` instead of `SchemaTree`

![Image](https://github.com/ydb-platform/ydb-embedded-ui/assets/67755036/86474fd6-6f5e-43b3-97cc-bf73c63d377d)

**Comment by Raubzeug** [comment]
@antonkovalenko @adameat Nonetheless, don't we want to show R/O label inside the schema tree? It's rather more clear as for me.
And about icon. Animated part is not a good idea if speaking about performance. But what if we add a small lock?
Something like
<img width="381" alt="Screenshot 2024-07-03 at 09 45 34" src="https://github.com/ydb-platform/ydb-embedded-ui/assets/42094364/3e244f2c-dc5d-4d8f-8138-ccc70a940a7f">

**Comment by artemmufazalov** [comment]
> @antonkovalenko @adameat Nonetheless, don't we want to show R/O label inside the schema tree? It's rather more clear as for me.

It's how our schema works. We cannot display `R/O` label without this object describe. So, to display labels in schema tree, we need either request data for all entities, which is rather uneffective, or we can display it only for opened entities, which is not very good as well.

**Comment by Raubzeug** [comment]
> It's how our schema works. We cannot display `R/O` label without this object describe. So, to display labels in schema tree, we need either request data for all entities, which is rather uneffective, or we can display it only for opened entities, which is not very good as well.

I've totally missed this "small" thing :(
And isn't it possible to return any additional field for children in describe?

**Comment by adameat** [comment]
> I've totally missed this "small" thing :( And isn't it possible to return any additional field for children in describe?

it won't be cheap
