### ISSUE TITLE
Do not request sysinfo on Cluster page

### ISSUE THREAD

**Issue by artemmufazalov** [ydb-platform/ydb-embedded-ui#809]
sysinfo is used only on Overview and Versions tabs, it should be requested only there, there is no need to request it for other tabs (Databases, Nodes, Storage)

**Comment by adameat** [comment]
for inspiration...

![image](https://github.com/ydb-platform/ydb-embedded-ui/assets/34044711/f7b6f7af-86dd-4272-875f-bec13e87a8d9)
