### ISSUE TITLE
[tablets tab] display tablets as table

### ISSUE THREAD

**Issue by antonkovalenko** [ydb-platform/ydb-embedded-ui#843]
1. remove filters
2. display tablets of selected schema object as table
3. tabletid leads to tablet page. Tablet id is a link
4. Actions: restart. Don't add other buttons.

![Image](https://github.com/ydb-platform/ydb-embedded-ui/assets/692649/fb7e6914-5fee-434e-8782-88dd80b066a2)

**Comment by artemmufazalov** [comment]
Tablet states to colors are here: https://github.com/ydb-platform/ydb-embedded-ui/blob/main/src/utils/tablet.ts

**Comment by artemmufazalov** [comment]
There is a restart control on Tablet page: https://github.com/ydb-platform/ydb-embedded-ui/blob/main/src/containers/Tablet/TabletControls/TabletControls.tsx
