### ISSUE TITLE
update via dataquery doesn't change values

### ISSUE THREAD

**Issue by antonkovalenko** [ydb-platform/ydb-embedded-ui#844]
### Problem

Update table query doesn't change values in a table though operation is marked as success.
Affects main and 24-1

### Steps to reproduce

1. select a row in any table by primary key value
2. run update query that changes any non-pk field's value
3. select this row by primary key

### Expected Result

Value of an updated column was changed

### Actual result

After second select you can see the initial value as is update was not applied

**Comment by artemmufazalov** [comment]
`UPDATE` with `execute-data` and `execute-query` doesn't work (only `execute-script` works)

There is no error, response looks similar to `execute-script`.

Not a frontend issue

**Comment by antonkovalenko** [comment]
@StekPerepolnen take a look please

**Comment by StekPerepolnen** [comment]
https://github.com/ydb-platform/ydb/pull/5013

**Comment by antonkovalenko** [comment]
please don't forget to merge into 24-1

**Comment by StekPerepolnen** [comment]
https://github.com/ydb-platform/ydb/pull/5081
