### ISSUE TITLE
display default value for column

### ISSUE THREAD

**Issue by antonkovalenko** [ydb-platform/ydb-embedded-ui#870]
Extended schema tab at diagnostics must display default value for a column

**Comment by artemmufazalov** [comment]
@antonkovalenko 

1. Is it correct, that we should use `value` field from `DefaultFromLiteral` ?

2. Should this column be hidden, if there are no default values for the table columns (we do this way for autoIncrement)? 

3. How we name this column? Just "Default" or "Default value"

**Comment by antonkovalenko** [comment]
> 1. Is it correct, that we should use `value` field from `DefaultFromLiteral` ?

Let's ask @gridnevvvit who is closer to the author

> 3. Should this column be hidden, if there are no default values for the table columns (we do this way for autoIncrement)?

yes

> 5. How we name this column? Just "Default" or "Default value"

I would use word Default
