### ISSUE TITLE
display autoincrement on schema tab

### ISSUE THREAD

**Issue by antonkovalenko** [ydb-platform/ydb-embedded-ui#871]
Extended schema tab in Diagnostics mode must display auto increment info.

1. If any column in table has `DefaultFromSequence` truthy property, add`Autoincrement` column into Schema table.
2. If column has `DefaultFromSequence` truthy property, add tick into the new column (like in `NotNull`)
<img width="765" alt="Screenshot 2024-06-06 at 15 25 20" src="https://github.com/ydb-platform/ydb-embedded-ui/assets/42094364/5bd5a671-67a0-4714-93e0-e5e418b35e45">

**Comment by Raubzeug** [comment]
@gridnevvvit Vitaly, could you please confirm that I pointed out the correct column property?

**Comment by gridnevvvit** [comment]
okay, i think that statement in the issue is correct.
