### ISSUE TITLE
[ydb dwh] add useful attributes to coltable tabs

### ISSUE THREAD

**Issue by antonkovalenko** [ydb-platform/ydb-embedded-ui#885]
1. Don't display metrics that has not value, like these:
```
LastAccessTime . . . . . .  N/A
LastUpdateTime . . . . . . .N/A
```
2. Rename `Columntable` to `Column-oriented table` like in [docs](https://ydb.tech/docs/en/concepts/datamodel/table#olap-data-types)

3. At the top section `AUTO_PARTITIONING_MIN_PARTITIONS_COUNT ` should be displayed as well, according to [docs](https://ydb.tech/docs/en/concepts/datamodel/table#olap-data-types)

4. Partitioning section should be displayed just like it was written in sql query - `PARTITION BY HASH(id)`

**Further improvements are to be discussed during a meeting in a couple of weeks**

**Comment by SloNN** [comment]
I suggest that the following list should be displayed:
1. Type - Column-based table
2. Created
3. Updated
4. Row count
5. Disk size

You can show below (or better to show somewhere separate):
1. Partition count
2. Type of partitioning (by size, by load etc)

I suggest not to show:
1. Id
2. Version

**Comment by antonkovalenko** [comment]
https://github.com/ydb-platform/ydb/issues/6672 waiting for this one

**Comment by artemmufazalov** [comment]
> You can show below (or better to show somewhere separate):
> 
> 2. Type of partitioning (by size, by load etc)
> 
@SloNN Where can I get info about column table partitioning? Currently, we have only `ColumnTableDescription.Sharding.HashSharding`, so we display `Sharding: hash` if it is present

**Comment by artemmufazalov** [comment]
Regarding Min and Max number of partitions - we don't have these params for columns tables, do they exist somewhere?

**Comment by SloNN** [comment]
> Where can I get info about column table partitioning? Currently, we have only `ColumnTableDescription.Sharding.HashSharding`, so we display `Sharding: hash` if it is present

We will resolve it here https://github.com/ydb-platform/ydb/issues/6672

**Comment by SloNN** [comment]
This information will be provided in this issue https://github.com/ydb-platform/ydb/issues/7620
