### ISSUE TITLE
rework overview pane in schema browser

### ISSUE THREAD

**Issue by adameat** [ydb-platform/ydb-embedded-ui#906]
take as example PersQueueGroup:

<img width="540" alt="image" src="https://github.com/ydb-platform/ydb-embedded-ui/assets/34044711/709f8938-4e55-4095-8ab6-604d930f611b">

1. show Type (PathType) for every schema type
2. show SubType (PathSubType) if it's not EPathSubTypeEmpty
3. show PathId if it's not 0
4. show PathVersion
5. show created time if it's not 0

for EPathTypeTable:
1. show Partitions count = len(TablePartitions)

for EPathTypeColumnTable:
1. show Partitions count = len(ColumnTableDescription.Sharding.ColumnShards)

for EPathTypeColumnStore:
1. show Partitions count = len(ColumnStoreDescription.ColumnShards)

for EPathTypeExtSubDomain: (database)
1. show Paths (DomainDescription.PathsInside)
2. show Shards (DomainDescription.ShardsInside)

**don't show rows with 0 values at all. we don't need "Create time .... 0" or "Create time .... unknown"**

**Comment by antonkovalenko** [comment]
let's output just table name without database name
