### ISSUE TITLE
Add create folder action to database/folder context menu

### ISSUE THREAD

**Issue by antonkovalenko** [ydb-platform/ydb-embedded-ui#915]
1. only relative path
2. name with slashes `dir2/dir3` creates a tree of directories
3. full path of the directory being created is displayed as i type

**Comment by antonkovalenko** [comment]
@adameat will help with a handler to create a dir

**Comment by antonkovalenko** [comment]
https://github.com/ydb-platform/ydb/issues/5552

**Comment by Raubzeug** [comment]
https://github.com/ydb-platform/ydb/pull/5617

**Comment by antonkovalenko** [comment]
when back doesn't support this call I can see Network error message
It not crit
Let's do it another way next time? Obviously we are going to have different versions.
![error-on-old-version](https://github.com/ydb-platform/ydb-embedded-ui/assets/692649/173be3e6-00b2-48c4-a3ad-4a2d201406e3)
