### ISSUE TITLE
storage not available when system tables are broken

### ISSUE THREAD

**Issue by adameat** [ydb-platform/ydb-embedded-ui#937]
the problem is with static group. it's overflowed and no system tablets are able to run.

![image](https://github.com/ydb-platform/ydb-embedded-ui/assets/34044711/783e1650-08bd-4b12-9e20-fc6a01715f22)

![image](https://github.com/ydb-platform/ydb-embedded-ui/assets/34044711/5356725d-269e-4b6e-a146-7026420a2b4b)

![image](https://github.com/ydb-platform/ydb-embedded-ui/assets/34044711/9d4556e3-16a7-46d8-8674-1fca2dcfcee7)

![image](https://github.com/ydb-platform/ydb-embedded-ui/assets/34044711/e69647e4-9930-43df-aa57-06f56a66274c)

**Comment by antonkovalenko** [comment]
@adameat says it's not reproducable any more
