### ISSUE TITLE
Improve ACL

### ISSUE THREAD

**Issue by Raubzeug** [ydb-platform/ydb-embedded-ui#939]
1) Access Type. In 99.99999% it is "Allow". Let's check if another value is presented, and add this column only if it does.
2) Access Rights. If backend return high-level rights, it will be handy to show only them (maybe with tooltip, where full list of rights is shown?)
3) Subject. Should be visible (without ellipsis). If backend return type of subject, it may be useful to show icons (user, robot, group, etc) to visually identify what subject is it.
4) Inheritance Type. It takes a lot of space. Maybe we can show icons for every type?

5) Maybe we should abandon table in favor of cards or definition list?

**Comment by adameat** [comment]
backend improvements are here: https://github.com/ydb-platform/ydb/pull/5814
