### ISSUE TITLE
Add tracing header for requests from app

### ISSUE THREAD

**Issue by Raubzeug** [ydb-platform/ydb-embedded-ui#941]
https://w3c.github.io/trace-context/#traceparent-header

**Comment by adameat** [comment]
to start a trace in http request it needs to add "X-Want-Trace: 1" header.
in response will be "traceresponse" header, containing trace details (https://w3c.github.io/trace-context/#traceresponse-header)

it needed to add this optional behavior (via settings) for /viewer/query handlers.

if query returns traceresponse header it needs to build a hyperlink from monitoring ui base ("https://monitoring.yandex-team.ru/projects/kikimr/traces/") and the second part of traceresponse header (trace id). for eaxmple: "https://monitoring.yandex-team.ru/projects/kikimr/traces/8443ccb806f32a6d7c46f84c35a27d09".

I think that we can get monitoring ui base from meta/cluster handler.

**Comment by adameat** [comment]
to specify how much details we want in a trace, we could add header:
X-Trace-Verbosity: <verbosity>
where verbosity is from 1 to 15 (15 is maximum verbosity).
if this header specified, then X-Want-Trace header is optional. it's implied.
default verbosity is 15.

**Comment by antonkovalenko** [comment]
will be done as a part of [#1060](https://github.com/ydb-platform/ydb-embedded-ui/issues/1060)
